export const ADMIN_CAPABILITIES = [
  'admin.access',
  'users.manage',
  'content.read',
  'content.edit',
  'content.review',
  'content.publish',
  'crm.read',
  'crm.manage',
  'crm.export',
  'orders.read',
  'orders.manage',
  'orders.sync',
  'market.read',
  'market.manage',
  'market.self',
  'tree.read',
  'tree.export',
  'events.manage',
  'events.read',
  'events.checkin',
  'events.export',
  'unity.read',
  'unity.manage',
  'radio.read',
  'radio.manage',
  'backstage.read',
  'backstage.manage',
  'auctions.read',
  'auctions.manage',
  'analytics.read',
  'analytics.export',
  'config.manage',
  'tree.update',
  'community.read',
  'community.moderate',
  'audit.read',
];

/**
 * Contrato canónico de roles del panel. Lo comparten el dominio TS, las
 * migraciones y el bootstrap Node para que nombres y capacidades iniciales
 * no se desalineen.
 */
export const ADMIN_ROLES_META = [
  {
    key: 'owner',
    name: 'Owner',
    description: 'Configuración sensible, usuarios, roles, auditoría y todos los módulos.',
    capabilities: '*',
  },
  {
    key: 'admin',
    name: 'Administrador',
    description: 'Operación completa de módulos autorizados y publicación de contenido.',
    capabilities: [
      'admin.access',
      'content.read',
      'content.edit',
      'content.review',
      'content.publish',
      'crm.read',
      'crm.manage',
      'crm.export',
      'orders.read',
      'orders.manage',
      'orders.sync',
      'market.read',
      'market.manage',
      'tree.read',
      'tree.export',
      'events.manage',
      'events.read',
      'events.checkin',
      'events.export',
      'unity.read',
      'unity.manage',
      'radio.read',
      'radio.manage',
      'backstage.read',
      'backstage.manage',
      'auctions.read',
      'auctions.manage',
      'analytics.read',
      'analytics.export',
      'community.read',
      'tree.update',
      'community.moderate',
      'audit.read',
    ],
  },
  {
    key: 'editor',
    name: 'Editor',
    description: 'Crear, editar y preparar contenido, lanzamientos, eventos y activos.',
    capabilities: [
      'admin.access',
      'content.read',
      'content.edit',
      'content.review',
      'events.read',
      'events.manage',
    ],
  },
  {
    key: 'operador',
    name: 'Operador',
    description:
      'Atender solicitudes, actualizar Tree/mercado/radio y consultar operaciones asignadas.',
    capabilities: [
      'admin.access',
      'crm.read',
      'crm.manage',
      'crm.export',
      'orders.read',
      'orders.manage',
      'market.read',
      'tree.read',
      'tree.update',
      'tree.export',
      'events.read',
      'events.manage',
      'events.checkin',
      'events.export',
      'unity.read',
      'unity.manage',
      'radio.read',
      'backstage.read',
      'backstage.manage',
    ],
  },
  {
    key: 'moderador',
    name: 'Moderador',
    description: 'Revisar y moderar comunidad.',
    capabilities: ['admin.access', 'community.read', 'community.moderate'],
  },
  {
    key: 'lector',
    name: 'Lector',
    description: 'Consulta de métricas y datos explícitamente asignados.',
    capabilities: [
      'admin.access',
      'content.read',
      'crm.read',
      'orders.read',
      'market.read',
      'tree.read',
      'events.read',
      'unity.read',
      'radio.read',
      'community.read',
      'backstage.read',
      'analytics.read',
    ],
  },
  {
    key: 'vendedor',
    name: 'Vendedor',
    description: 'Acceso comercial limitado al vendedor vinculado y a sus registros propios.',
    capabilities: ['admin.access', 'crm.read', 'orders.read', 'market.read', 'market.self'],
  },
];
